services:
   mysql:
    image: mysql:8.4.5
    environment:
      MYSQL_DATABASE: devteam
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_USER: dev-docker
      MYSQL_PASSWORD: root
    ports:
      - '3306'
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql -h localhost -u root -p$${MYSQL_ROOT_PASSWORD} -e 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: